development:
  adapter: mongodb
  host: localhost
  database: usergroupmanager

test: &TEST
  adapter: mongodb
  host: localhost
  database: usergroupmanager_test

production:
  adapter: mongodb
  host: localhost
  database: wordbadger